import { Chip } from './chip';

export const CHIPS: Chip[] = [
    {   id: 1,
        name: "Cannon",
        description: "Cannon attack to 1 enemy",
        element: "Null",
        damage: 40,
        class: "Standard",
        chipCode: ["A", "B", "C", "*"],
        megabytes: 6,
        image: "../assets/Images/BattleChips/Cannon.png",
      },
      {   id: 2,
        name: "HiCannon",
        description: "Cannon attack to 1 enemy",
        element: "Null",
        class: "Standard",
        damage: 100,
        chipCode: ["L", "M", "N", "*"],
        megabytes: 24,
        image: "../assets/Images/BattleChips/HiCannon.png",
      },
      {   id: 3,
        name: "M-Cannon",
        description: "Cannon attack to 1 enemy",
        element: "Null",
        class: "Standard",
        damage: 180,
        chipCode: ["R","S", "T", "*"],
        megabytes: 38,
        image: "../assets/Images/BattleChips/M-Cannon.png",
      },
      {   id: 4,
        name: "Air Shot",
        description: "Knock enemy back 1 square",
        element: "Wind",
        class: "Standard",
        damage: 20,
        chipCode: ["*"],
        megabytes: 4,
        image: "../assets/Images/BattleChips/Airshot.png",
      },
      {   id: 5,
        name: "Vulcan1",
        description: "3-shot to pierce 1 panel!",
        element: "Null",
        class: "Standard",
        damage: 10,
        chipCode: ["B", "D", "S", "*"],
        megabytes: 5,
        image: "../assets/Images/BattleChips/Vulcan1.png",
      }

      /*---For use in the chipCatalogue.json---
      ,
    {   
        "id": ,
        "name": "",
        "description":"",
        "element" : "Null",
        "class": "Standard",
        "damage": ,
        "chipCode": ["A", "B", "C", "*"],
        "megabytes": 0,
        "image": "../assets/Images/BattleChips/.png"
    },*/
]