import { Chip } from './chip';

export const CHIPS: Chip[] = [
    {   id: 0,
        name: "Cannon",
        description: "Cannon attack to 1 enemy",
        element: "Null",
        damage: 40,
        class: "Standard",
        chipCode: ["A", "B", "C", "*"],
        image: "../assets/Images/BattleChips/Cannon.png",
      },
      {   id: 1,
        name: "HiCannon",
        description: "Cannon attack to 1 enemy",
        element: "Null",
        class: "Standard",
        damage: 80,
        chipCode: ["A", "B", "C", "*"],
        image: "../assets/Images/BattleChips/HiCannon.png",
      },
      {   id: 2,
        name: "M-Cannon",
        description: "Cannon attack to 1 enemy",
        element: "Null",
        class: "Standard",
        damage: 120,
        chipCode: ["A", "B", "C", "*"],
        image: "../assets/Images/BattleChips/M-Cannon.png",
      }
]